# Generated by Django 3.1.2 on 2021-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210125_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='porfile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
